### ISSUE TITLE
Padding issue on mobile view of the slider nav

### ISSUE THREAD

**Issue by Oscarj-8** [klassno3/scentopia#8]
The nav links are too close to the edge of the slider, giving it p-2 would help. and also placing the search bar and the nav links to the top instead of the center of the slider would be better
![issueone](https://github.com/klassno3/scentopia/assets/101042769/9bcc3af6-996d-4178-8db1-25d05bf30e33)

**Comment by Oscarj-8** [comment]
![image](https://github.com/klassno3/scentopia/assets/101042769/35656501-f0ec-4464-8dd0-6d13934e682d)
consider this one also

**Comment by Zekud** [comment]
right it would be better

**Comment by klassno3** [comment]
i made the font size smaller and added padding since most smart phone are above 300px we will be fine. this is what it looks like at 277px.
![photo_2024-02-26_23-29-18](https://github.com/klassno3/scentopia/assets/101359180/006f4425-bfd2-49b9-903d-9577c5e42a02)
